# Generated by Django 4.1 on 2024-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('icon_image', models.ImageField(upload_to='icons/')),
                ('graduate_at', models.IntegerField(choices=[(24, 24), (25, 25), (26, 26), (27, 27), (28, 28)], verbose_name='卒業年')),
                ('graduate_at_summer', models.BooleanField(default=True)),
            ],
        ),
    ]
